version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - 5432:5432
    env_file:
    - docker.env
    networks:
    - postgres
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
    - pgdata:/var/lib/postgresql/data
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8000:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - 3030:3000
      - 9229:9229
    networks:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin

  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
        context: .
        target: production
        dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
        - 3000:3000
        - 9229:9229
    networks:
        - postgres
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped
 
networks:
  postgres:
volumes:
  pgdata: